export const UPDATE_SHOP = 'UPDATE_SHOP',
    ADD_PRODUCT = ' ADD_PRODUCT',
    UPDATE_PRODUCT = 'UPDATE_PRODUCT',
    DELETE_PRODUCT = 'DELETE_PRODUCT',
    UPDATE_SHOPS_LIST = 'UPDATE_SHOPS_LIST',
    FIND_SHOP = 'FIND_SHOP';


